####################################################################################################
# +----------------------------------------------------------------------------------------------+ #
# |                    ___ _           _     ___ _                            _                  | #
# |                   / __\ |__   __ _| |_  / __\ |__   __ _ _ __  _ __   ___| |___              | #
# |                  / /  | '_ \ / _` | __|/ /  | '_ \ / _` | '_ \| '_ \ / _ \ / __|             | #
# |                 / /___| | | | (_| | |_/ /___| | | | (_| | | | | | | |  __/ \__ \             | #
# |                 \____/|_| |_|\__,_|\__\____/|_| |_|\__,_|_| |_|_| |_|\___|_|___/             | #
# |                                                                                              | #
# |                                                                                              | #
# |  SOURCE CODE: https://github.com/ZiiMs/ZiiM-Crates                                           | #
# |  BUG REPORTS: https://github.com/ZiiMs/ZiiM-Crates/issues                                   | #
# |                                                                                              |
# +----------------------------------------------------------------------------------------------+ #
####################################################################################################

# Storage settings

# MYSQL settings
data:
  # Address to your database
  address: 'localhost'
  # Port of your database
  port: '3306'
  # User of your database
  user: 'root'
  # Password of your database
  password: ''
  # The database to connect to
  database: 'minecraft'