name: ChatChannel
version: ${project.version}
main: me.ziim.chatchannel.ChatChannel
api-version: 1.16
authors: [ ZiiM ]
description: A simple lightweight chat channels mod
commands:
  createchannel:
    description: Create a new channel
    usage: §eUSAGE /createchannel <channel prefix> <channel color> <channel title>
    permission: cc.createchannel
  join:
    description: Join a channel
    usage: §eUSAGE /join <channel title>
    permission: cc.join
  editprefix:
    description: Edit prefix of a channel
    usage: §eUSAGE /editprefix <channel name> <new prefix>
    permission: cc.editprefix
  editchannel:
    description: Edit channel name
    usage: §eUSAGE /editchannel <prefix> <new name>
    permission: cc.editchannel
  editcolor:
    description: Edit color of a channel
    usage: §eUSAGE /editcolor <prefix> <new color>
    permission: cc.editcolor
  channels:
    description: Displays channels you are in.
    usage: §eUSAGE /channels
    permission: cc.channels
  listchannels:
    description: Displays all channels.
    usage: §eUSAGE /listchannels
    permission: cc.listchannels
